src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $title = null;

    #[ORM\Column(length: 100)]
    private ?string $author = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?bool $is_published = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Comment::class)]
    private Collection $comments;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image):self
    {
        $this->image = $image;
        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }


}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class  Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?User $author = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Article $article = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?bool $IsPublished = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $PublishedDate = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->IsPublished;
    }

    public function setIsPublished(bool $IsPublished): self
    {
        $this->IsPublished = $IsPublished;

        return $this;
    }

    public function getPublishedDate(): ?\DateTimeInterface
    {
        return $this->PublishedDate;
    }

    public function setPublishedDate(\DateTimeInterface $PublishedDate): self
    {
        $this->PublishedDate = $PublishedDate;

        return $this;
    }
}

templates/agence.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    <title>L'Agence</title>
{% endblock %}

{% block main %}
    <h2 class="article-title">DEEP SPACE, La révolution spatiale, c'est maintenant !</h2>
    <article class="mono">
        <img class="article-img" src="{{ asset('assets/img/2.png') }}">
        <h3 class="article-sub">AGENCE</h3>
        <p class="article-text">Cras semper auctor neque vitae tempus quam pellentesque nec.
            Mattis molestie a iaculis at erat pellentesque adipiscing commodo.
            Tellus id interdum velit laoreet id donec ultrices.
            Morbi tincidunt ornare massa eget egestas purus.
            Nec nam aliquam sem et tortor consequat id.
            Nec tincidunt praesent semper feugiat. Mi quis hendrerit dolor magna. Fa
            mes ac turpis egestas sed. Convallis tellus id interdum velit.
            Viverra accumsan in nisl nisi scelerisque eu ultrices vitae.
            Et tortor at risus viverra adipiscing. Nibh praesent tristique magna sit amet purus gravida quis.
            Amet volutpat consequat mauris nunc congue nisi. Vitae aliquet nec ullamcorper sit.
            Porta non pulvinar neque laoreet suspendisse. Tortor dignissim convallis aenean et tortor at risus viverra.
            Vel pretium lectus quam id leo in.</p>
        <img class="article-img" src="{{ asset('assets/img/agency.jpeg') }}">
        <h3 class="article-sub">RECHERCHES</h3>
        <p class="article-text">Cras semper auctor neque vitae tempus quam pellentesque nec.
            Mattis molestie a iaculis at erat pellentesque adipiscing commodo.
            Tellus id interdum velit laoreet id donec ultrices.
            Morbi tincidunt ornare massa eget egestas purus.
            Nec nam aliquam sem et tortor consequat id.
            Nec tincidunt praesent semper feugiat. Mi quis hendrerit dolor magna. Fa
            mes ac turpis egestas sed. Convallis tellus id interdum velit.
            Viverra accumsan in nisl nisi scelerisque eu ultrices vitae.
            Et tortor at risus viverra adipiscing. Nibh praesent tristique magna sit amet purus gravida quis.
            Amet volutpat consequat mauris nunc congue nisi. Vitae aliquet nec ullamcorper sit.
            Porta non pulvinar neque laoreet suspendisse. Tortor dignissim convallis aenean et tortor at risus viverra.
            Vel pretium lectus quam id leo in.</p>
        <img class="article-img" src="{{ asset('assets/img/hypersonic.jpeg') }}">
        <h3 class="article-sub">PROJETS</h3>
        <p class="article-text">Cras semper auctor neque vitae tempus quam pellentesque nec.
            Mattis molestie a iaculis at erat pellentesque adipiscing commodo.
            Tellus id interdum velit laoreet id donec ultrices.
            Morbi tincidunt ornare massa eget egestas purus.
            Nec nam aliquam sem et tortor consequat id.
            Nec tincidunt praesent semper feugiat. Mi quis hendrerit dolor magna. Fa
            mes ac turpis egestas sed. Convallis tellus id interdum velit.
            Viverra accumsan in nisl nisi scelerisque eu ultrices vitae.
            Et tortor at risus viverra adipiscing. Nibh praesent tristique magna sit amet purus gravida quis.
            Amet volutpat consequat mauris nunc congue nisi. Vitae aliquet nec ullamcorper sit.
            Porta non pulvinar neque laoreet suspendisse. Tortor dignissim convallis aenean et tortor at risus viverra.
            Vel pretium lectus quam id leo in.</p>
    </article>
{% endblock %}

templates/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    <title>{{ article.title }}</title>
{% endblock %}

{% block main %}

{% include 'preheader.html.twig' %}
    <article class="mono">
        <img class="article-img" src="{{ asset('uploads/images/'~ article.image)}}" alt="{{ article.title }}">
        <h1 class="headline">{{ article.title }}</h1>
        <p class="subtitle">{{ article.category.title }}</p>
        <p class="description">{{ article.content }}</p>
    </article>
    <section class="comments">
        <h2 class="comments-title">Commentaires</h2>
        {% for comment in article.comments %}
            {% if comment.isPublished%}
            <article class="comment">
               <h3 class="comment-author">{{ comment.author.name }}</h3>
                <p class="comment-text">{{ comment.content }}</p>
                <p class="comment-date"> {{ comment.publishedDate|date('d/m/Y') }}</p>
            </article>
            {% endif %}
        {% endfor %}
    </section>
    {% if app.user %}
        <section class="comment-block">
            <h2 class="comment-title">Ajoutez votre commentaire</h2>
                {% if form %}
                    <div class="comment-form">{{ form(form) }}</div>
                {% endif %}
        </section>
    {% endif %}
{% endblock %}

templates/articles.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    <title>Tous les articles</title>
{% endblock %}

{% block main %}

{% include ('preheader.html.twig') %}
    <section class="searchtool">
        <form class="searchbar" method="get" action="{{ path('articles-search') }}">
            <input class="searchbar" type="text" name="search">
            <input class="button-box" type="submit">
        </form>
    </section>
    <h2 class="section-title">TOUT NOS ARTICLES</h2>
    <section class="articles">
        {% for article in articles %}
            {% if article.IsPublished %}
                <article class="list">
                    <img class="list-img" src="{{asset('uploads/images/'~ article.image)}}" alt="{{ article.title }}">
                    <h2 class="box-title">{{ article.title }}</h2>
                    <p class="subtitle"> écrit par {{ article.author }}</p>
                    <p class="subtitle">{{ article.category.title }}</p>
                    <p class="description">{{ article.description }}</p>
                    <a class="button-boxes" href="{{ path('article-page', {'id': article.id}) }}">Lire <span class="chevron">></span></a>
                </article>
            {% else %}
                <p>Cet article n'est pas encore publié</p>
            {% endif %}
        {% endfor %}
    </section>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ asset("assets/css/style.css") }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('assets/img/2.png') }}">

        {% block title %}
            <title>Document</title>
        {% endblock %}
    </head>
    <body>
        <header>
            <a href="{{ path('home') }}"><img class="header-logo" src="{{ asset("assets/img/1.png") }}"></a>
            <nav>
                <a href="{{ path('home') }}">Accueil</a>
                <a href="{{ path('articles-page') }}">Articles</a>
                <a href="{{ path('telescop-page')}}">Téléscope GJR-KING</a>
                <a href="{{ path('project-page') }}">Projet DS-1</a>
                {% if app.user %}
                    <a href="{{ path('app_logout') }}">Deconnexion</a>
                {% else %}
                    <a href="{{ path('app_login') }}">Connexion</a>
                    <a href="{{ path('sign-up') }}">Inscription</a>
                {% endif %}
            </nav>
            <button type="button" aria-label="toggle curtain navigation" class="nav-toggler">
                <span class="line l1"></span>
                <span class="line l2"></span>
                <span class="line l3"></span>
            </button>
            {% if app.user %}
                <section class="toolbar">
                        <p class="pseudo"> Bonjour {{ app.user.name }}</p>
                </section>
            {% endif %}
        </header>
        <main>

            {% block main %}

            {% endblock %}

        </main>
        <footer>
            <img class="footer-logo" src="{{ asset('assets/img/2.png') }}">
            <div class="footer-info">
                <p>DEEP SPACE</p>
                <p>300 AVENUE DE LA SOMME</p>
                <p>MÉRIGNAC FRANCE</p>
                <p>COPYRIGHT © | RAMILLON GAËTAN </p>
            </div>
        </footer>

        <script src="{{ asset('assets/js/script.js') }}"></script>
    </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    <title>Page d'accueil</title>
{% endblock %}

{% block main %}

{% include ('preheader.html.twig') %}

    <section class="presentation-box">
        <h2 class="section-title">EXPLORER</h2>
        <div class="boxes">
            <div class="box">
                <h3>LE PROJET DEEP SPACE DS-1</h3>
                <a class="button-box" href="{{ path('project-page') }}">En savoir +</a>
            </div>
            <div class="semi-boxes">
                <div class="second-box">
                    <h3>TOUTES NOS PUBLICATIONS</h3>
                    <a class="button-boxes" href="{{ path('articles-page') }}">En savoir +</a>
                </div>

                <div class="third-box">
                    <h3>TELESCOPE GJR-KING</h3>
                    <a class="button-boxes" href="{{ path('telescop-page') }}">En savoir +</a>
                </div>
            </div>
        </div>
    </section>
    <h2 class="section-title">NOS DERNIERS ARTICLES</h2>

    <section class="articles-box">

        {% for article in lastArticles %}
        <article class="list">
            <img class="list-img" src="{{asset('uploads/images/'~ article.image)}}" alt="{{ article.title }}">
            <h2 class="box-title">{{ article.title }}</h2>
            <p class="subtitle"> écrit par {{ article.author }}</p>
            <p class="subtitle">{{ article.category.title }}</p>
            <p class="description">{{ article.description }}</p>
            <a class="button-boxes" href="{{ path('article-page', {'id': article.id}) }}">Lire <span class="chevron">></span></a>
        </article>
        {% endfor %}
    </section>
{% endblock %}

templates/preheader.html.twig
<section class="pre-header">
    <h1>RECHERCHE<br>
    INNOVATION<br>
    EXPLORATION</h1>
    <a class="button-prehead" href="{{ path('agence-page') }}">L' AGENCE <span class="chevron">></span></a>
</section>

templates/project.html.twig
{% extends ('base.html.twig') %}

{% block title %}
    <title>Projet DS-1</title>
{% endblock %}

{% block main %}

{% include ('preheader.html.twig') %}
    <h2 class="article-title">LE PROJET DEEP SPACE DS-1</h2>
    <article class="mono">
        <h3 class="article-sub">Le futur de l'exploration spatiale !</h3>
        <img class="article-img" src="{{ asset("assets/img/hypersonic.jpeg") }}" alt="hyperplane">
        <p class="article-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Augue ut lectus arcu bibendum at varius.
            Morbi tempus iaculis urna id volutpat lacus laoreet non. Orci eu lobortis elementum nibh tellus molestie nunc non.
            Orci nulla pellentesque dignissim enim sit amet venenatis urna. Magna eget est lorem ipsum dolor sit amet consectetur.
            Id faucibus nisl tincidunt eget nullam. Semper feugiat nibh sed pulvinar proin gravida.
            Convallis convallis tellus id interdum velit. Ipsum dolor sit amet consectetur adipiscing.
            Nisl tincidunt eget nullam non nisi est sit. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit.</p>
        <h3 class="article-sub">Notre Technologie</h3>
        <p class="article-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Augue ut lectus arcu bibendum at varius. Morbi tempus iaculis urna id volutpat lacus laoreet non. Orci eu lobortis elementum nibh tellus molestie nunc non. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Magna eget est lorem ipsum dolor sit amet consectetur. Id faucibus nisl tincidunt eget nullam. Semper feugiat nibh sed pulvinar proin gravida. Convallis convallis tellus id interdum velit. Ipsum dolor sit amet consectetur adipiscing. Nisl tincidunt eget nullam non nisi est sit. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit.</p>
        <img class="article-img" src="{{ asset("assets/img/plans.jpeg") }}" alt="plans">
    </article>

{% endblock %}

templates/search_articles.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    {% include 'preheader.html.twig' %}
    {% for article in articles %}
        <article class="list">
            <img class="list-img" src="{{asset('uploads/images/'~ article.image)}}" alt="{{ article.title }}">
            <h2 class="box-title">{{ article.title }}</h2>
            <p class="subtitle"> écrit par {{ article.author }}</p>
            <p class="subtitle">{{ article.category.title }}</p>
            <p class="description">{{ article.description }}</p>
            <a class="button-boxes" href="{{ path('article-page', {'id': article.id}) }}">Lire <span class="chevron">></span></a>
        </article>
    {% endfor %}
{% endblock %}

templates/telescop.html.twig
{% extends ('base.html.twig') %}

{% block title %}
    <title>GJR-KING</title>
{% endblock %}

{% block main %}

{% include ('preheader.html.twig') %}
    <section>
        <article class="mono">
            <img class="article-img" src="{{ asset('assets/img/4.png') }}">
            <h3 class="article-sub">Un jour, un cliché</h3>
            <p class="article-text">Cras semper auctor neque vitae tempus quam pellentesque nec.
                Mattis molestie a iaculis at erat pellentesque adipiscing commodo.
                Tellus id interdum velit laoreet id donec ultrices.
                Morbi tincidunt ornare massa eget egestas purus.
                Nec nam aliquam sem et tortor consequat id.
                Nec tincidunt praesent semper feugiat. Mi quis hendrerit dolor magna. Fa
                mes ac turpis egestas sed. Convallis tellus id interdum velit.
                Viverra accumsan in nisl nisi scelerisque eu ultrices vitae.
                Et tortor at risus viverra adipiscing. Nibh praesent tristique magna sit amet purus gravida quis.
                Amet volutpat consequat mauris nunc congue nisi. Vitae aliquet nec ullamcorper sit.
                Porta non pulvinar neque laoreet suspendisse. Tortor dignissim convallis aenean et tortor at risus viverra.
                Vel pretium lectus quam id leo in.</p>
            <div class="astronomy">
                <h3 class="article-sub">{{ data.title }}</h3>
                <p class="article-text">{{ data.date }}</p>
                {%if (data.media_type == "video") %}
                    <iframe class="article-video" src="{{ data.url }}"> </iframe>
                {% else %}
                    <img class="article-img" src="{{ data.url }}">
                {% endif %}
                <p class="article-text">Explanation : {{ data.explanation }}</p>
            </div>
        </article>
    </section>


{% endblock %}